// Auto-generated entities index
// This file is automatically generated by the TypeORM infrastructure generator

import { CourseModule } from './course.module.entity';
import { CourseContent } from './course.content.entity';
import { Course } from './course.entity';
import { LearningPathCourses } from './learning.path.courses.entity';
import { LearningPath } from './learning.path.entity';
import { UserLearning } from './user.learning.entity';
import { Certificates } from './certificates.entity';
import { RolePermission } from './role.permission.entity';
import { CourseEnrollment } from './course.enrollment.entity';
import { LearningPathEnrollment } from './learning.path.enrollment.entity';

export const Entities = [
    CourseModule,
    CourseContent,
    Course,
    LearningPathCourses,
    LearningPath,
    UserLearning,
    Certificates,
    CourseEnrollment,
    LearningPathEnrollment,
    RolePermission,
];
